version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'simple-bank'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: '3309'
    ports:
      - '3309:3309'
    expose:
      - '3309'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
