index:
  path: /
  controller: SimpleBank\Controller\MainController::index

bank_branches_list:
  path: /bank_branches
  controller: SimpleBank\Controller\BankBranchController::list

bank_branches_add:
  path: /bank_branches/add
  controller: SimpleBank\Controller\BankBranchController::add

users_list:
  path: /users
  controller: SimpleBank\Controller\UserController::list

users_bank_branches_add:
  path: /users/bank_branches/{bankBranchId}
  controller: SimpleBank\Controller\UserController::add

users_show:
  path: /users/{userId}
  controller: SimpleBank\Controller\UserController::show

